### ISSUE TITLE
请教一个问题，我现在把你的工程改了下，现在发现了一些问题

### ISSUE THREAD

**Issue by bugfan** [yeild/jigsaw#10]
加入了发请求的部分，但是目前只能在ｐｃ端使用了，我用模拟器或者手机打开，也可以看到图，也可以滑动，但是在移动端或者模拟器就无法发送数据了，发送的都是空，而且也不报错，但是ｐｃ端却正常，这是啥情况？
请看我部署的地址:`http://www.zoux.xin:8085/api/static/`

**Comment by yeild** [comment]
你这个改了后好像滑块不能正常显示了
![image](https://user-images.githubusercontent.com/23716085/71566069-52079380-2aef-11ea-8522-389483cd1b40.png)
这边也看不到你的代码，PC可以移动端不行的话建议查看是否是touch事件的问题

**Comment by bugfan** [comment]
不是啊，滑块我改成矩形了，扣出来的改成阴影的了。

**Comment by bugfan** [comment]
Fun Guy ，你是小卡球迷吗

**Comment by yeild** [comment]
> Fun Guy ，你是小卡球迷吗

哈哈，是的

**Comment by bugfan** [comment]
一样啊，我也是小卡球迷，哈哈

**Comment by bugfan** [comment]
我写ｇｏ的

**Comment by yeild** [comment]
> 　不是啊，滑块我改成矩形了，扣出来的改成阴影的了。

你把源码贴出来，或者挂在codepen之类的网页上我看下呢

**Comment by bugfan** [comment]
https://github.com/bugfan/bugfan.github.io/blob/master/jigsaw.js 这个

**Comment by bugfan** [comment]
加个微信或者ｑｑ，我请教你一下，我的是908958194
