### ISSUE TITLE
请问一下,那个切块不要边框,只要阴影怎么添加呢

### ISSUE THREAD

**Issue by Soilder666** [yeild/jigsaw#16]
试过了shadowColor喝shadowBlur那个属性.但是只能给缺陷的地方加.不能加到切块上

**Comment by yeild** [comment]
边框是stroke，不要边框去掉stroke就可以了

**Comment by Soilder666** [comment]
加阴影的呢,试过在draw里面加shadowColor和shadowBlur但是只能加到那个白底上,不能加到切出来的那块上面

**Comment by yeild** [comment]
> 加阴影的呢,试过在draw里面加shadowColor和shadowBlur但是只能加到那个白底上,不能加到切出来的那块上面

因为clip只保留路径内的块, 路径外的阴影会被裁剪掉，要实现需要的效果可能需要额外的路径覆盖上去
![image](https://user-images.githubusercontent.com/23716085/88358059-1cced580-cda0-11ea-9b18-611d9371b4ec.png)

**Comment by Soilder666** [comment]
有啥好的具体实现方法,吗....
