### ISSUE TITLE
如何在vue项目中使用呢？

### ISSUE THREAD

**Issue by Lilac-Dream** [yeild/jigsaw#18]
1、我尝试在vue里面使用，可是失败了……所以想知道如何才能在vue里面调用使用？？能否做成vue的组件呢？
2、demo是否可以添加一个没封装的，使用jigsaw.js文件调用的例子？

先谢谢作者啦，这个滑动验证码做的真棒！

**Comment by yeild** [comment]
1. 在mounted生命周期里像demo那样初始化就可以了
2. 不太明白意思，是指import/require那样引入吗？最近是打算重构一番，但是比较忙不一定能很快上

**Comment by Lilac-Dream** [comment]
1、我不知道如何能用"jigsaw.js"来进行使用，只会使用大佬你封装好的"jigsaw.min.js"文件。
所以我想要一份：不用封装好的min文件，用原文件"jigsaw.js"使用的例子~~
2、是指import/require那样引入，因为这样会更好用些~（好像有点过分伸手党的情况~）

我是前端萌新，请多多包涵。谢谢你！

**Comment by yeild** [comment]
可以下载src路径下的js和css文件，拷贝到你的项目中，然后将jigsaw.js最后的
![image](https://user-images.githubusercontent.com/23716085/91020307-e4cbe400-e624-11ea-8403-005b5c962655.png)
改为
```
export default  {
  init: function (opts) {
    return new Jigsaw(opts).init()
  }
}
```
然后在mouted里init就可以了~

**Comment by Lilac-Dream** [comment]
非常感谢！成功加进去了，谢谢你！
