### ISSUE TITLE
想导出重新刷新图片功能，return里面应该怎么写？

### ISSUE THREAD

**Issue by Lilac-Dream** [yeild/jigsaw#19]
导出重新刷新图片功能，想直接调用jigsaw.reset_pic实现图片刷新，文件里面的return应该怎么写呀？

代码：
export default {
  init: function(opts) {
    return new Jigsaw(opts).init();
  },
  reset_pic: function() {
    // 下面这个return应该怎么写呀？
    return *****;
  }
};

先谢谢作者大大啦~

**Comment by yeild** [comment]
可以在init方法中返回reset等想要调用的方法:
```
  init () {
    this.initDOM()
    this.initImg()
    this.bindEvents()
+   return {
+     reset: this.reset.bind(this)
+   }
  }

...

export default {
  init: function (opts) {
    return new Jigsaw(opts).init()
  }
}

...

import Jigsaw from ...

const jigsaw = Jigsaw.init()
jigsaw.reset()
```

**Comment by Lilac-Dream** [comment]
好的！谢谢

**Comment by Lilac-Dream** [comment]
尝试了几次发现我还是没能成功~

报错图片：
![image](https://user-images.githubusercontent.com/49761134/91275987-75d0c580-e7b3-11ea-94c4-c73c0ef53b96.png)
![image](https://user-images.githubusercontent.com/49761134/91276035-87b26880-e7b3-11ea-9f56-10fd25a38674.png)

我的修改：
![image](https://user-images.githubusercontent.com/49761134/91276064-939e2a80-e7b3-11ea-86aa-91af0dd995cd.png)
![image](https://user-images.githubusercontent.com/49761134/91276092-9f89ec80-e7b3-11ea-90fc-96e2b0e8d986.png)
![image](https://user-images.githubusercontent.com/49761134/91276126-aca6db80-e7b3-11ea-9a64-d28b9a52c82e.png)

我尝试在init里面再添加el，就会生成多个验证码了~所以还是不知道怎么做了~~

**Comment by yeild** [comment]
![image](https://user-images.githubusercontent.com/23716085/91279901-a9fab500-e7b8-11ea-8c89-f3e0e22afdb4.png)
Jigsaw.init()这里要传{el}参数，生成多个验证码应该是你在其他地方还调用了init

**Comment by Lilac-Dream** [comment]
之前初始化(mounted)的时候添使用了init，我删掉初始化后，现在只使用按钮触发。

虽然最上面的那个验证码会刷新，但是会在验证码下面出现新的。

我只想通过外部一个btn执行reset操作，不知道我是哪里出现了错误~
我感觉是每次调用jigsaw.reset都重新执行了一次init里面的所有内容导致重复添加？
`init() {
    this.initDOM();  
    this.initImg();
    this.bindEvents();
    return {
      reset: this.reset.bind(this)
    };
  }
`

当前代码：
![image](https://user-images.githubusercontent.com/49761134/91282536-0f03da00-e7bc-11ea-9eca-8538590e5276.png)

效果（按钮触发的methods的 jigsaw_reset）:
![image](https://user-images.githubusercontent.com/49761134/91283698-838b4880-e7bd-11ea-8462-bea7acf025f2.png)

**Comment by yeild** [comment]
每次调用init的时候就会new一个实例，所以肯定不能点一次按钮init一次。。初始化的代码在哪里，在初始化的地方保存reset方法，然后点击按钮的时候去调用那个方法

**Comment by Lilac-Dream** [comment]
实现了，非常感谢！会弄了！

**Comment by Lilac-Dream** [comment]
![image](https://user-images.githubusercontent.com/49761134/91287027-c8b17980-e7c1-11ea-84e0-e803e068bd95.png)

**Comment by yeild** [comment]
也没有啥特别相关的关键词，就是变量作用域，文件模块之类的，这是vue吧，也可以看父子组件通信相关的，看起来好像你的button是个独立的组件，如果init的地方是button的父组件，你可以button click的时候emit一个事件,父组件监听到事件了去调用reset方法

**Comment by Lilac-Dream** [comment]
嗯嗯，谢谢你，太棒啦，开心~！

**Comment by yeild** [comment]
像你这样写就是用闭包保存了reset方法，作用域相关的(调用写反了哦，jigsaw_reset.reset())

**Comment by Lilac-Dream** [comment]
嗯嗯，我这let变量和function的名字都起重复了~~
现在已经好用了~~作者大大你真的太棒啦！
一个小问题耽误你这么长时间，我都不好意思啦~嘿嘿~

**Comment by Lilac-Dream** [comment]
原来~~根本不用写".reset()"~~写上还报错~

这是我现在实现的代码，如果有其他人遇到我一样问题的就做参考吧~
![image](https://user-images.githubusercontent.com/49761134/91292021-863f6b00-e7c8-11ea-8025-cd5cfd473522.png)
![image](https://user-images.githubusercontent.com/49761134/91292050-8e97a600-e7c8-11ea-9757-d3f9bbfc259d.png)
![image](https://user-images.githubusercontent.com/49761134/91292069-95beb400-e7c8-11ea-8594-5ab24d551d08.png)
