### ISSUE TITLE
随机截取背景canvas图片到block内，截取出的不是一整个方块吗？

### ISSUE THREAD

**Issue by old-atong** [yeild/jigsaw#4]
initImg方法中getImageData(this.x - 3, y, L, L)  这行代码，截取的是效果如图

![image](https://user-images.githubusercontent.com/26064084/50721526-e23d1380-10fb-11e9-962d-3675f5446af9.png)

**Comment by old-atong** [comment]
请问是怎么做到截取出小拼图  在block中只显示了stroke()绘制的图形呢？ 第134行截取的是方块，请指教🙏

**Comment by old-atong** [comment]
已解决，是我的代码顺序错了。

**Comment by yeild** [comment]
抱歉哦之前没来得及看，解决了就好啦
