### ISSUE TITLE
可以实现网络图片库找不到从项目里的图片随机挑选吗？

### ISSUE THREAD

**Issue by 852675742** [yeild/jigsaw#5]
可以实现网络图片库找不到从项目里的图片随机挑选吗？

**Comment by yeild** [comment]
图片获取失败时会自动重新获取的，如果要从自己的项目里获取图片，可以重写这两个方法，将图片地址指向自己项目的路径

![5jqc7 nyz t7lfh4151v87](https://user-images.githubusercontent.com/23716085/51734363-43368680-20bf-11e9-85b6-75f20d245914.png)

![op g z5q7 aqh g x g](https://user-images.githubusercontent.com/23716085/51734285-0cf90700-20bf-11e9-99a7-8109ef6a3536.png)
