### ISSUE TITLE
怎么集成到vue里面去啊？

### ISSUE THREAD

**Issue by 852675742** [yeild/jigsaw#6]
怎么集成到vue里面去啊？

**Comment by yeild** [comment]
1. 在组件中引入jigsaw.js
2. 在mounted里边init

el可以用vue.$refs，或者直接用document.quertSelector

![yj7m t4o0o 66x0w 5b4dy](https://user-images.githubusercontent.com/23716085/51758737-6124db00-2101-11e9-88eb-8142945b5e24.png)
