### ISSUE TITLE
很实用也很方便，在谷歌，360之类的浏览器上都不是方块，但是火狐上就成了一方块

### ISSUE THREAD

**Issue by JasonHuoying** [yeild/jigsaw#7]
![@8FB (C_A )1}CFIE2Z 1JT](https://user-images.githubusercontent.com/31676365/59747202-0015c380-92ab-11e9-9011-6ab391d3ff1d.png)

![image](https://user-images.githubusercontent.com/31676365/59747322-3ce1ba80-92ab-11e9-9ed1-a3198eb2776a.png)

**Comment by yeild** [comment]
谢谢指正，已解决；目前使用 destination-over 代替 overlay，兼容性良好且效果与之前一致

**Comment by JasonHuoying** [comment]
点个赞，棒棒哒！！！

**Comment by liqin1059** [comment]
去老板电脑上把谷歌icon换成火狐🤔
