### ISSUE TITLE
web端拿来做单独的前端验证很好用！！不过老板又说想让截取的小拼图也有滑动验证效果，我在canvas里整了半天也没啥用，请问大佬这个好实现吗？

### ISSUE THREAD

**Issue by pwyGouxiong** [yeild/jigsaw#8]
web端拿来做单独的前端验证很好用！！不过小气的老板又说想让截取的小拼图也能按住拖拽实现滑动验证效果，在canvas里整了半天也没啥用，请问下大佬这个好实现吗？

**Comment by yeild** [comment]
可以的，那个小拼图也是元素可以直接加事件的哈 我已经加上了，下载下最新的js吧~

**Comment by pwyGouxiong** [comment]
好高效啊，请收下我的膝盖！！！

**Comment by yeild** [comment]
还好还好，事件处理器是现成的只加两行代码注册下就行了 我看网易也是可以直接拖拼图的，就加上了~
